### ISSUE TITLE
Cannot read property 'string' of undefined in latest release 2.4.1

### ISSUE THREAD

**Issue by alengel** [CognizantStudio/react-loader#62]
Hi there, we use react-loader on production and had it set to `^2.4.0` in our package.json. The latest release 2.4.1 is breaking on Travis with the following error:

Test suite failed to run
TypeError: Cannot read property 'string' of undefined
      
      at node_modules/react-loader/lib/react-loader.js:15:33
      at Object.<anonymous>.createReactClass.propTypes.className (node_modules/react-loader/lib/react-loader.js:6:22)
      at Object.<anonymous> (node_modules/react-loader/lib/react-loader.js:11:2)

Fixing it manually at 2.4.0 resolves this issue but thought you should know that the patch is breaking things.

**Comment by nicholasserra** [comment]
Thanks for the report! We're looking into this right now. Any additional info you can provide would be helpful, thanks :)

**Comment by mmw** [comment]
This might have just resulted from the deployer not running `npm install` before publishing

**Comment by marcgarreau** [comment]
That's our best guess too, @mmw. Please reopen if problem persists.

**Comment by mmw** [comment]
@marcgarreau that means a maintainer of this project needs to re-publish on npm. Ticket closed but still at version `2.4.1`, I think we expect `2.4.2` with a correct publish

**Comment by feitla** [comment]
We are still seeing this issue with `2.4.2`. Was this resolved in 2.4.2?

**Comment by nicholasserra** [comment]
@feitla  can you provide some context on your setup? We were thinking this may only be an issue for those who are not packing requirements in any way.

**Comment by mmw** [comment]
@nicholasserra as I commented above this seems to be an issue with the release... I experienced the same problem with a package I published after a similar refactor. I solved this for the time being by locking to `react-loader v2.4.1` but I believe the person deploying `react-loader` didnt run the build before publishing

**Comment by nicholasserra** [comment]
@mmw just pulled down 2.4.2 and it seems the js and jsx files are identical and up to date. That's the only build that happens for this package. Unless you're referring to something else? Thanks for the input and helping us debug this.

**Comment by mmw** [comment]
@nicholasserra oh I got a bit confused. Seems like `v2.4.2` was published on May 18th, it wasnt obvious to me that it was re-published. When I said I locked to `v2.4.1` above it was actually `v.2.4.0`.

`v2.4.2` doesn't break in my system and all seems fine. Thanks for looking into this and sorry for the confusion.

**Comment by nicholasserra** [comment]
@mmw Thanks for the confirmation :)

**Comment by feitla** [comment]
@nicholasserra  we are downloading your package via bower. And we are still getting the error for 2.4.2 from this bower package. Can you confirm?

**Comment by nicholasserra** [comment]
@feitla Looks like our bower config is pretty old. I'm wondering if bower is pulling an old version of this? (i'm not too well versed in how bower installs things). Can you check to see if the code is up to date with this package after the bower install? I'll give it a spin on my end too.

**Comment by feitla** [comment]
@nicholasserra I checked and we are loading the right version 2.4.2, and actually switched to the npm package to check if it was bower config causing this issue. 

Once I switched and got the npm packaged loaded, we are still seeing the issue. Would this have anything to do with us using `react-rails` gem instead of npm package? 

This error, `Uncaught TypeError: Cannot read property 'string' of undefined at react-loader.js 1:15`, does not exist in 2.4.0

**Comment by nicholasserra** [comment]
@feitla curious, are you also including these libraries on the page? We saw this issue when these weren't included.

https://github.com/CognizantStudio/react-loader/blob/d1bff53724ae1876909cf995a3b0d54810002046/examples/simple/index.html#L7-L11

Could be that the react gem isn't pulling these libraries. Especially since `prop-types` and `create-react-class` are recent additions.
